/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-03-27 at 20:35:03 UTC 
 * Modify at your own risk.
 */

package com.gottagged380.gamemanager.model;

/**
 * Model definition for GameRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GameRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer duration;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nameOfCreator;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> nameOfPlayers;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDuration() {
    return duration;
  }

  /**
   * @param duration duration or {@code null} for none
   */
  public GameRequest setDuration(java.lang.Integer duration) {
    this.duration = duration;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameOfCreator() {
    return nameOfCreator;
  }

  /**
   * @param nameOfCreator nameOfCreator or {@code null} for none
   */
  public GameRequest setNameOfCreator(java.lang.String nameOfCreator) {
    this.nameOfCreator = nameOfCreator;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getNameOfPlayers() {
    return nameOfPlayers;
  }

  /**
   * @param nameOfPlayers nameOfPlayers or {@code null} for none
   */
  public GameRequest setNameOfPlayers(java.util.List<java.lang.String> nameOfPlayers) {
    this.nameOfPlayers = nameOfPlayers;
    return this;
  }

  @Override
  public GameRequest set(String fieldName, Object value) {
    return (GameRequest) super.set(fieldName, value);
  }

  @Override
  public GameRequest clone() {
    return (GameRequest) super.clone();
  }

}
