/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-12 22:39:29 UTC)
 * on 2013-04-22 at 03:18:25 UTC 
 * Modify at your own risk.
 */

package com.gottagged380.gamemanager.model;

/**
 * Model definition for PlayerUpdateRespond.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PlayerUpdateRespond extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double distance;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double distence;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean hasEnded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String winner;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getDistance() {
    return distance;
  }

  /**
   * @param distance distance or {@code null} for none
   */
  public PlayerUpdateRespond setDistance(java.lang.Double distance) {
    this.distance = distance;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getDistence() {
    return distence;
  }

  /**
   * @param distence distence or {@code null} for none
   */
  public PlayerUpdateRespond setDistence(java.lang.Double distence) {
    this.distence = distence;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getHasEnded() {
    return hasEnded;
  }

  /**
   * @param hasEnded hasEnded or {@code null} for none
   */
  public PlayerUpdateRespond setHasEnded(java.lang.Boolean hasEnded) {
    this.hasEnded = hasEnded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public PlayerUpdateRespond setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWinner() {
    return winner;
  }

  /**
   * @param winner winner or {@code null} for none
   */
  public PlayerUpdateRespond setWinner(java.lang.String winner) {
    this.winner = winner;
    return this;
  }

  @Override
  public PlayerUpdateRespond set(String fieldName, Object value) {
    return (PlayerUpdateRespond) super.set(fieldName, value);
  }

  @Override
  public PlayerUpdateRespond clone() {
    return (PlayerUpdateRespond) super.clone();
  }

}
