/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-12 22:39:29 UTC)
 * on 2013-04-22 at 03:18:25 UTC 
 * Modify at your own risk.
 */

package com.gottagged380.gamemanager;

/**
 * Service definition for Gamemanager (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GamemanagerRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Gamemanager extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(com.google.api.client.googleapis.GoogleUtils.VERSION.equals("1.14.1-beta"),
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14.1-beta of google-api-client to run version " +
        "1.14.1-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://gottagged380.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "gamemanager/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Gamemanager(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Gamemanager(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Game collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Gamemanager gamemanager = new Gamemanager(...);}
   *   {@code Gamemanager.Game.List request = gamemanager.game().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Game game() {
    return new Game();
  }

  /**
   * The "game" collection of methods.
   */
  public class Game {

    /**
     * Create a request for the method "game.available".
     *
     * This request holds the parameters needed by the the gamemanager server.  After setting any
     * optional parameters, call the {@link Available#execute()} method to invoke the remote operation.
     *
     * @param name
     * @return the request
     */
    public Available available(java.lang.String name) throws java.io.IOException {
      Available result = new Available(name);
      initialize(result);
      return result;
    }

    public class Available extends GamemanagerRequest<com.gottagged380.gamemanager.model.AvailableGames> {

      private static final String REST_PATH = "availablegames/{name}";

      /**
       * Create a request for the method "game.available".
       *
       * This request holds the parameters needed by the the gamemanager server.  After setting any
       * optional parameters, call the {@link Available#execute()} method to invoke the remote
       * operation. <p> {@link
       * Available#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param name
       * @since 1.13
       */
      protected Available(java.lang.String name) {
        super(Gamemanager.this, "GET", REST_PATH, null, com.gottagged380.gamemanager.model.AvailableGames.class);
        this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Available setAlt(java.lang.String alt) {
        return (Available) super.setAlt(alt);
      }

      @Override
      public Available setFields(java.lang.String fields) {
        return (Available) super.setFields(fields);
      }

      @Override
      public Available setKey(java.lang.String key) {
        return (Available) super.setKey(key);
      }

      @Override
      public Available setOauthToken(java.lang.String oauthToken) {
        return (Available) super.setOauthToken(oauthToken);
      }

      @Override
      public Available setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Available) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Available setQuotaUser(java.lang.String quotaUser) {
        return (Available) super.setQuotaUser(quotaUser);
      }

      @Override
      public Available setUserIp(java.lang.String userIp) {
        return (Available) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String name;

      /**

       */
      public java.lang.String getName() {
        return name;
      }

      public Available setName(java.lang.String name) {
        this.name = name;
        return this;
      }

      @Override
      public Available set(String parameterName, Object value) {
        return (Available) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "game.create".
     *
     * This request holds the parameters needed by the the gamemanager server.  After setting any
     * optional parameters, call the {@link Create#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.gottagged380.gamemanager.model.GameRequest}
     * @return the request
     */
    public Create create(com.gottagged380.gamemanager.model.GameRequest content) throws java.io.IOException {
      Create result = new Create(content);
      initialize(result);
      return result;
    }

    public class Create extends GamemanagerRequest<com.gottagged380.gamemanager.model.GameRequestResponse> {

      private static final String REST_PATH = "createGame";

      /**
       * Create a request for the method "game.create".
       *
       * This request holds the parameters needed by the the gamemanager server.  After setting any
       * optional parameters, call the {@link Create#execute()} method to invoke the remote operation.
       * <p> {@link
       * Create#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.gottagged380.gamemanager.model.GameRequest}
       * @since 1.13
       */
      protected Create(com.gottagged380.gamemanager.model.GameRequest content) {
        super(Gamemanager.this, "POST", REST_PATH, content, com.gottagged380.gamemanager.model.GameRequestResponse.class);
      }

      @Override
      public Create setAlt(java.lang.String alt) {
        return (Create) super.setAlt(alt);
      }

      @Override
      public Create setFields(java.lang.String fields) {
        return (Create) super.setFields(fields);
      }

      @Override
      public Create setKey(java.lang.String key) {
        return (Create) super.setKey(key);
      }

      @Override
      public Create setOauthToken(java.lang.String oauthToken) {
        return (Create) super.setOauthToken(oauthToken);
      }

      @Override
      public Create setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Create) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Create setQuotaUser(java.lang.String quotaUser) {
        return (Create) super.setQuotaUser(quotaUser);
      }

      @Override
      public Create setUserIp(java.lang.String userIp) {
        return (Create) super.setUserIp(userIp);
      }

      @Override
      public Create set(String parameterName, Object value) {
        return (Create) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "game.join".
     *
     * This request holds the parameters needed by the the gamemanager server.  After setting any
     * optional parameters, call the {@link Join#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.gottagged380.gamemanager.model.JoinGame}
     * @return the request
     */
    public Join join(com.gottagged380.gamemanager.model.JoinGame content) throws java.io.IOException {
      Join result = new Join(content);
      initialize(result);
      return result;
    }

    public class Join extends GamemanagerRequest<com.gottagged380.gamemanager.model.JoinGame> {

      private static final String REST_PATH = "joinGame";

      /**
       * Create a request for the method "game.join".
       *
       * This request holds the parameters needed by the the gamemanager server.  After setting any
       * optional parameters, call the {@link Join#execute()} method to invoke the remote operation. <p>
       * {@link Join#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.gottagged380.gamemanager.model.JoinGame}
       * @since 1.13
       */
      protected Join(com.gottagged380.gamemanager.model.JoinGame content) {
        super(Gamemanager.this, "POST", REST_PATH, content, com.gottagged380.gamemanager.model.JoinGame.class);
      }

      @Override
      public Join setAlt(java.lang.String alt) {
        return (Join) super.setAlt(alt);
      }

      @Override
      public Join setFields(java.lang.String fields) {
        return (Join) super.setFields(fields);
      }

      @Override
      public Join setKey(java.lang.String key) {
        return (Join) super.setKey(key);
      }

      @Override
      public Join setOauthToken(java.lang.String oauthToken) {
        return (Join) super.setOauthToken(oauthToken);
      }

      @Override
      public Join setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Join) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Join setQuotaUser(java.lang.String quotaUser) {
        return (Join) super.setQuotaUser(quotaUser);
      }

      @Override
      public Join setUserIp(java.lang.String userIp) {
        return (Join) super.setUserIp(userIp);
      }

      @Override
      public Join set(String parameterName, Object value) {
        return (Join) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "game.status".
     *
     * This request holds the parameters needed by the the gamemanager server.  After setting any
     * optional parameters, call the {@link Status#execute()} method to invoke the remote operation.
     *
     * @param id
     * @param name
     * @return the request
     */
    public Status status(java.lang.Long id, java.lang.String name) throws java.io.IOException {
      Status result = new Status(id, name);
      initialize(result);
      return result;
    }

    public class Status extends GamemanagerRequest<com.gottagged380.gamemanager.model.GameStatus> {

      private static final String REST_PATH = "checkGameStatus/{id}/{name}";

      /**
       * Create a request for the method "game.status".
       *
       * This request holds the parameters needed by the the gamemanager server.  After setting any
       * optional parameters, call the {@link Status#execute()} method to invoke the remote operation.
       * <p> {@link
       * Status#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @param name
       * @since 1.13
       */
      protected Status(java.lang.Long id, java.lang.String name) {
        super(Gamemanager.this, "POST", REST_PATH, null, com.gottagged380.gamemanager.model.GameStatus.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
        this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
      }

      @Override
      public Status setAlt(java.lang.String alt) {
        return (Status) super.setAlt(alt);
      }

      @Override
      public Status setFields(java.lang.String fields) {
        return (Status) super.setFields(fields);
      }

      @Override
      public Status setKey(java.lang.String key) {
        return (Status) super.setKey(key);
      }

      @Override
      public Status setOauthToken(java.lang.String oauthToken) {
        return (Status) super.setOauthToken(oauthToken);
      }

      @Override
      public Status setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Status) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Status setQuotaUser(java.lang.String quotaUser) {
        return (Status) super.setQuotaUser(quotaUser);
      }

      @Override
      public Status setUserIp(java.lang.String userIp) {
        return (Status) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public Status setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String name;

      /**

       */
      public java.lang.String getName() {
        return name;
      }

      public Status setName(java.lang.String name) {
        this.name = name;
        return this;
      }

      @Override
      public Status set(String parameterName, Object value) {
        return (Status) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Player collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Gamemanager gamemanager = new Gamemanager(...);}
   *   {@code Gamemanager.Player.List request = gamemanager.player().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Player player() {
    return new Player();
  }

  /**
   * The "player" collection of methods.
   */
  public class Player {

    /**
     * Create a request for the method "player.update".
     *
     * This request holds the parameters needed by the the gamemanager server.  After setting any
     * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.gottagged380.gamemanager.model.PlayerUpdate}
     * @return the request
     */
    public Update update(com.gottagged380.gamemanager.model.PlayerUpdate content) throws java.io.IOException {
      Update result = new Update(content);
      initialize(result);
      return result;
    }

    public class Update extends GamemanagerRequest<com.gottagged380.gamemanager.model.PlayerUpdateRespond> {

      private static final String REST_PATH = "playerUpdate";

      /**
       * Create a request for the method "player.update".
       *
       * This request holds the parameters needed by the the gamemanager server.  After setting any
       * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
       * <p> {@link
       * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.gottagged380.gamemanager.model.PlayerUpdate}
       * @since 1.13
       */
      protected Update(com.gottagged380.gamemanager.model.PlayerUpdate content) {
        super(Gamemanager.this, "POST", REST_PATH, content, com.gottagged380.gamemanager.model.PlayerUpdateRespond.class);
      }

      @Override
      public Update setAlt(java.lang.String alt) {
        return (Update) super.setAlt(alt);
      }

      @Override
      public Update setFields(java.lang.String fields) {
        return (Update) super.setFields(fields);
      }

      @Override
      public Update setKey(java.lang.String key) {
        return (Update) super.setKey(key);
      }

      @Override
      public Update setOauthToken(java.lang.String oauthToken) {
        return (Update) super.setOauthToken(oauthToken);
      }

      @Override
      public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Update) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Update setQuotaUser(java.lang.String quotaUser) {
        return (Update) super.setQuotaUser(quotaUser);
      }

      @Override
      public Update setUserIp(java.lang.String userIp) {
        return (Update) super.setUserIp(userIp);
      }

      @Override
      public Update set(String parameterName, Object value) {
        return (Update) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Gamemanager}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Gamemanager}. */
    @Override
    public Gamemanager build() {
      return new Gamemanager(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GamemanagerRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGamemanagerRequestInitializer(
        GamemanagerRequestInitializer gamemanagerRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(gamemanagerRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
